@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":MarkAsFavouriteCommandParser" as MarkAsFavouriteCommandParser LOGIC_COLOR
participant "m:MarkAsFavouriteCommand" as MarkAsFavouriteCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box "Commons Core" LOGIC_COLOR_T1
participant "ParserUtil" as ParserUtil LOGIC_COLOR
participant "index:Index" as Index LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
participant "personToEdit:Person" as PersonToEdit MODEL_COLOR
participant "markedPerson:Person" as MarkedPerson MODEL_COLOR
end box

[-> LogicManager : execute("mark 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("mark 1")
activate AddressBookParser

create MarkAsFavouriteCommandParser
AddressBookParser -> MarkAsFavouriteCommandParser : MarkAsFavouriteCommandParser()
activate MarkAsFavouriteCommandParser

MarkAsFavouriteCommandParser --> AddressBookParser
deactivate MarkAsFavouriteCommandParser

AddressBookParser -> MarkAsFavouriteCommandParser : parse("1")
activate MarkAsFavouriteCommandParser

MarkAsFavouriteCommandParser -> ParserUtil : parseIndex("1")
activate ParserUtil

create Index
ParserUtil -> Index : fromOneBased(1)
activate Index

Index --> ParserUtil
deactivate Index

ParserUtil --> MarkAsFavouriteCommandParser
deactivate ParserUtil

create MarkAsFavouriteCommand
MarkAsFavouriteCommandParser -> MarkAsFavouriteCommand : MarkAsFavouriteCommand(index)
activate MarkAsFavouriteCommand

MarkAsFavouriteCommand --> MarkAsFavouriteCommandParser
deactivate MarkAsFavouriteCommand

MarkAsFavouriteCommandParser --> AddressBookParser : m
deactivate MarkAsFavouriteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
MarkAsFavouriteCommandParser -[hidden]-> AddressBookParser
destroy MarkAsFavouriteCommandParser

AddressBookParser --> LogicManager : m
deactivate AddressBookParser

LogicManager -> MarkAsFavouriteCommand : execute(model)
activate MarkAsFavouriteCommand

MarkAsFavouriteCommand -> Model : getFilteredPersonList()
activate Model

Model --> MarkAsFavouriteCommand
deactivate Model

create PersonToEdit
MarkAsFavouriteCommand -> PersonToEdit : lastShownList.get(index.getZeroBased())
activate PersonToEdit

PersonToEdit --> MarkAsFavouriteCommand
deactivate PersonToEdit

alt personToEdit is already favourite
MarkAsFavouriteCommand --> LogicManager

else personToEdit is not favourite
create MarkedPerson
MarkAsFavouriteCommand -> MarkedPerson : Person(..., true, ...)
activate MarkedPerson

MarkedPerson --> MarkAsFavouriteCommand
deactivate MarkedPerson

MarkAsFavouriteCommand -> Model : setPerson(personToEdit, markedPerson)
activate Model

Model --> MarkAsFavouriteCommand
deactivate Model

create CommandResult
MarkAsFavouriteCommand -> CommandResult : CommandResult(feedbackToUser)
activate CommandResult

CommandResult --> MarkAsFavouriteCommand
deactivate CommandResult

MarkAsFavouriteCommand --> LogicManager
end

deactivate MarkAsFavouriteCommand

[<--LogicManager
deactivate LogicManager
@enduml
